### PR TITLE
TicktHub DDL Muskaan #46

### PR DESCRIPTION
**Pull request by Muskaan906**
Uploaded TicktHub DDL 
issue: System - Design Database and DDL - Backend #46

### CODE REVIEW

**Review by tatkg24 — CHANGES_REQUESTED** [review]
Please see [PR #49](https://github.com/JoheeYeom0103/TicktHub/pull/69) for information about how we should potentially change this.

**Review by JoheeYeom0103 — COMMENTED** [review]
I have left review on the pull request "testing ddl via insert statements & select statements #49 #69"

**Review by kevinruann — APPROVED** [review]
The DDL looks good!

**Comment by Muskaan906** [comment]
Closing pull request, issue resolved as DDL was updated by zaynb

**Pull request closed without merging**
